#version 450 core
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct FogData{
    vec3 radiance;
    float transmittance;
};

layout(std140, binding = 8) buffer VolumetricFogBuffer {
    FogData[] fogDatas;
};

uniform uvec2 screenResolution;

void main(){
    uint fogIndex = gl_GlobalInvocationID.x + gl_GlobalInvocationID.y * screenResolution.x;
    fogDatas[fogIndex].radiance = vec3(0.0);
    fogDatas[fogIndex].transmittance = 1;
}